# Generated by Django 5.1.1 on 2024-10-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comet',
            fields=[
                ('comet_name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('planet_name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Satelite',
            fields=[
                ('satelite_name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
